name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: gradlew 권한부여
        run: chmod +x gradlew
      - name: 환경변수 파일 생성
        run: echo "${{secrets.ENVS}}" > .env
      - name: Gradle 빌드
        run: ./gradlew clean build
      - name: 도커 빌드 & 푸쉬
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/handal .
          docker push ${{ secrets.DOCKER_USERNAME }}/handal
      - name: 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_IP}}
          username: ec2-user
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            mkdir -p ./config
            echo "${{secrets.ENVS}}" > ./config/.env
            docker ps 
            docker container stop app
            docker container rm app
            docker pull ${{ secrets.DOCKER_USERNAME }}/handal
            docker run -d -p 8080:8080 --env-file ~/config/.env -e TZ=Asia/Seoul --name app ${{ secrets.DOCKER_USERNAME }}/handal
            docker image prune -f
